### ISSUE TITLE
The grid_search.sh could not run correctly

### ISSUE THREAD

**Issue by Huarong** [npow/memnn#3]
/home/work/.jumbo/lib/python2.7/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:29: UserWarning: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770..  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
/home/work/.jumbo/lib/python2.7/site-packages/theano/scan_module/scan_perform_ext.py:85: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
Traceback (most recent call last):
  File "main.py", line 245, in <module>
    main()
  File "main.py", line 242, in main
    model.train(args.n_epochs)
  File "main.py", line 153, in train
    self.create_train(lenW, len(f))
  File "main.py", line 118, in create_train
    updates=updates)
  File "/home/work/.jumbo/lib/python2.7/site-packages/theano/compile/function.py", line 223, in function
    profile=profile)
  File "/home/work/.jumbo/lib/python2.7/site-packages/theano/compile/pfunc.py", line 490, in pfunc
    no_default_updates=no_default_updates)
  File "/home/work/.jumbo/lib/python2.7/site-packages/theano/compile/pfunc.py", line 217, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{sub,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by npow** [comment]
Should be fixed now.
